### ISSUE TITLE
Mypy type annotations

### ISSUE THREAD

**Issue by markheik** [zhinst/zhinst-toolkit#136]
Add `mypy` (Added in #125) to check code type hints.

Please feel free to pick a file, make `mypy` pass and create a PR.

Once finished: Create PR and remove the file from [setup.cfg](https://github.com/zhinst/zhinst-toolkit/blob/main/setup.cfg)  `[mypy]`-section

----------------------------------------------------------------

The following files not fully covered by passing checks:

- [x] src/zhinst/toolkit/nodetree/helper.py #159
- [x] src/zhinst/toolkit/session.py #164
- [x] src/zhinst/toolkit/waveform.py #139
- [x] src/zhinst/toolkit/command_table.py #164
- [x]  src/zhinst/toolkit/nodetree/nodetree.py #164
 - [x] src/zhinst/toolkit/nodetree/node.py #164
 - [x] src/zhinst/toolkit/nodetree/connection_dict.py #164
 - [x] src/zhinst/toolkit/driver/modules/base_module.py #159
 - [x] src/zhinst/toolkit/driver/modules/shfqa_sweeper.py #164
 - [x] src/zhinst/toolkit/driver/modules/daq_module.py #159
 - [x] src/zhinst/toolkit/driver/modules/sweeper_module.py #159
 - [x] src/zhinst/toolkit/driver/devices/uhfqa.py #164
 - [x] src/zhinst/toolkit/driver/devices/hdawg.py #159
 - [x] src/zhinst/toolkit/driver/devices/base.py #159
 - [x] src/zhinst/toolkit/driver/nodes/readout.py #159
 - [x] src/zhinst/toolkit/driver/nodes/spectroscopy.py #159
 - [x] src/zhinst/toolkit/driver/nodes/command_table_node.py #159
 - [x] src/zhinst/toolkit/driver/nodes/generator.py #159
 - [x] src/zhinst/toolkit/driver/nodes/awg.py #159

**Comment by tobiasah** [comment]
no file are ignored during linting any more. 🥳
